from dataclasses import dataclass

from kirin.ir.attrs import Attribute
from kirin.ir.types import (
    Const,
    Generic,
    Literal,
    PyClass,
    TypeAttribute,
    TypeVar,
    Union,
)

@dataclass
class _TypeAttribute(Attribute):
    def is_subseteq_Union(self, other: Union) -> bool: ...
    def is_subseteq_Literal(self, other: Literal) -> bool: ...
    def is_subseteq_TypeVar(self, other: TypeVar) -> bool: ...
    def is_subseteq_Const(self, other: Const) -> bool: ...
    def is_subseteq_PyClass(self, other: PyClass) -> bool: ...
    def is_subseteq_Generic(self, other: Generic) -> bool: ...
    def is_subseteq_fallback(self, other: TypeAttribute) -> bool: ...
