import ast
import sys

from kirin.lowering.result import Result
from kirin.lowering.state import LoweringState

class FromPythonAST:
    @property
    def names(self) -> list[str]: ...
    def lower(self, ctx: LoweringState, node: ast.AST) -> Result: ...
    def unreachable(self, ctx: LoweringState, node: ast.AST) -> Result: ...
    def lower_Module(self, ctx: LoweringState, node: ast.Module) -> Result: ...
    def lower_Interactive(
        self, ctx: LoweringState, node: ast.Interactive
    ) -> Result: ...
    def lower_Expression(self, ctx: LoweringState, node: ast.Expression) -> Result: ...
    def lower_FunctionDef(
        self, ctx: LoweringState, node: ast.FunctionDef
    ) -> Result: ...
    def lower_AsyncFunctionDef(
        self, ctx: LoweringState, node: ast.AsyncFunctionDef
    ) -> Result: ...
    def lower_ClassDef(self, ctx: LoweringState, node: ast.ClassDef) -> Result: ...
    def lower_Return(self, ctx: LoweringState, node: ast.Return) -> Result: ...
    def lower_Delete(self, ctx: LoweringState, node: ast.Delete) -> Result: ...
    def lower_Assign(self, ctx: LoweringState, node: ast.Assign) -> Result: ...
    def lower_AugAssign(self, ctx: LoweringState, node: ast.AugAssign) -> Result: ...
    def lower_AnnAssign(self, ctx: LoweringState, node: ast.AnnAssign) -> Result: ...
    def lower_For(self, ctx: LoweringState, node: ast.For) -> Result: ...
    def lower_AsyncFor(self, ctx: LoweringState, node: ast.AsyncFor) -> Result: ...
    def lower_While(self, ctx: LoweringState, node: ast.While) -> Result: ...
    def lower_If(self, ctx: LoweringState, node: ast.If) -> Result: ...
    def lower_With(self, ctx: LoweringState, node: ast.With) -> Result: ...
    def lower_AsyncWith(self, ctx: LoweringState, node: ast.AsyncWith) -> Result: ...
    def lower_Raise(self, ctx: LoweringState, node: ast.Raise) -> Result: ...
    def lower_Try(self, ctx: LoweringState, node: ast.Try) -> Result: ...
    def lower_Assert(self, ctx: LoweringState, node: ast.Assert) -> Result: ...
    def lower_Import(self, ctx: LoweringState, node: ast.Import) -> Result: ...
    def lower_ImportFrom(self, ctx: LoweringState, node: ast.ImportFrom) -> Result: ...
    def lower_Global(self, ctx: LoweringState, node: ast.Global) -> Result: ...
    def lower_Nonlocal(self, ctx: LoweringState, node: ast.Nonlocal) -> Result: ...
    def lower_Expr(self, ctx: LoweringState, node: ast.Expr) -> Result: ...
    def lower_Pass(self, ctx: LoweringState, node: ast.Pass) -> Result: ...
    def lower_Break(self, ctx: LoweringState, node: ast.Break) -> Result: ...
    def lower_Continue(self, ctx: LoweringState, node: ast.Continue) -> Result: ...
    def lower_Slice(self, ctx: LoweringState, node: ast.Slice) -> Result: ...
    def lower_BoolOp(self, ctx: LoweringState, node: ast.BoolOp) -> Result: ...
    def lower_BinOp(self, ctx: LoweringState, node: ast.BinOp) -> Result: ...
    def lower_UnaryOp(self, ctx: LoweringState, node: ast.UnaryOp) -> Result: ...
    def lower_Lambda(self, ctx: LoweringState, node: ast.Lambda) -> Result: ...
    def lower_IfExp(self, ctx: LoweringState, node: ast.IfExp) -> Result: ...
    def lower_Dict(self, ctx: LoweringState, node: ast.Dict) -> Result: ...
    def lower_Set(self, ctx: LoweringState, node: ast.Set) -> Result: ...
    def lower_ListComp(self, ctx: LoweringState, node: ast.ListComp) -> Result: ...
    def lower_SetComp(self, ctx: LoweringState, node: ast.SetComp) -> Result: ...
    def lower_DictComp(self, ctx: LoweringState, node: ast.DictComp) -> Result: ...
    def lower_GeneratorExp(
        self, ctx: LoweringState, node: ast.GeneratorExp
    ) -> Result: ...
    def lower_Await(self, ctx: LoweringState, node: ast.Await) -> Result: ...
    def lower_Yield(self, ctx: LoweringState, node: ast.Yield) -> Result: ...
    def lower_YieldFrom(self, ctx: LoweringState, node: ast.YieldFrom) -> Result: ...
    def lower_Compare(self, ctx: LoweringState, node: ast.Compare) -> Result: ...
    def lower_Call(self, ctx: LoweringState, node: ast.Call) -> Result: ...
    def lower_FormattedValue(
        self, ctx: LoweringState, node: ast.FormattedValue
    ) -> Result: ...
    def lower_JoinedStr(self, ctx: LoweringState, node: ast.JoinedStr) -> Result: ...
    def lower_Constant(self, ctx: LoweringState, node: ast.Constant) -> Result: ...
    def lower_NamedExpr(self, ctx: LoweringState, node: ast.NamedExpr) -> Result: ...
    def lower_TypeIgnore(self, ctx: LoweringState, node: ast.TypeIgnore) -> Result: ...
    def lower_Attribute(self, ctx: LoweringState, node: ast.Attribute) -> Result: ...
    def lower_Subscript(self, ctx: LoweringState, node: ast.Subscript) -> Result: ...
    def lower_Starred(self, ctx: LoweringState, node: ast.Starred) -> Result: ...
    def lower_Name(self, ctx: LoweringState, node: ast.Name) -> Result: ...
    def lower_List(self, ctx: LoweringState, node: ast.List) -> Result: ...
    def lower_Tuple(self, ctx: LoweringState, node: ast.Tuple) -> Result: ...
    def lower_Del(self, ctx: LoweringState, node: ast.Del) -> Result: ...
    def lower_Load(self, ctx: LoweringState, node: ast.Load) -> Result: ...
    def lower_Store(self, ctx: LoweringState, node: ast.Store) -> Result: ...
    def lower_And(self, ctx: LoweringState, node: ast.And) -> Result: ...
    def lower_Or(self, ctx: LoweringState, node: ast.Or) -> Result: ...
    def lower_Add(self, ctx: LoweringState, node: ast.Add) -> Result: ...
    def lower_BitAnd(self, ctx: LoweringState, node: ast.BitAnd) -> Result: ...
    def lower_BitOr(self, ctx: LoweringState, node: ast.BitOr) -> Result: ...
    def lower_BitXor(self, ctx: LoweringState, node: ast.BitXor) -> Result: ...
    def lower_Div(self, ctx: LoweringState, node: ast.Div) -> Result: ...
    def lower_FloorDiv(self, ctx: LoweringState, node: ast.FloorDiv) -> Result: ...
    def lower_LShift(self, ctx: LoweringState, node: ast.LShift) -> Result: ...
    def lower_Mod(self, ctx: LoweringState, node: ast.Mod) -> Result: ...
    def lower_Mult(self, ctx: LoweringState, node: ast.Mult) -> Result: ...
    def lower_MatMult(self, ctx: LoweringState, node: ast.MatMult) -> Result: ...
    def lower_Pow(self, ctx: LoweringState, node: ast.Pow) -> Result: ...
    def lower_RShift(self, ctx: LoweringState, node: ast.RShift) -> Result: ...
    def lower_Sub(self, ctx: LoweringState, node: ast.Sub) -> Result: ...
    def lower_Invert(self, ctx: LoweringState, node: ast.Invert) -> Result: ...
    def lower_Not(self, ctx: LoweringState, node: ast.Not) -> Result: ...
    def lower_UAdd(self, ctx: LoweringState, node: ast.UAdd) -> Result: ...
    def lower_USub(self, ctx: LoweringState, node: ast.USub) -> Result: ...
    def lower_Eq(self, ctx: LoweringState, node: ast.Eq) -> Result: ...
    def lower_Gt(self, ctx: LoweringState, node: ast.Gt) -> Result: ...
    def lower_GtE(self, ctx: LoweringState, node: ast.GtE) -> Result: ...
    def lower_In(self, ctx: LoweringState, node: ast.In) -> Result: ...
    def lower_Is(self, ctx: LoweringState, node: ast.Is) -> Result: ...
    def lower_IsNot(self, ctx: LoweringState, node: ast.IsNot) -> Result: ...
    def lower_Lt(self, ctx: LoweringState, node: ast.Lt) -> Result: ...
    def lower_LtE(self, ctx: LoweringState, node: ast.LtE) -> Result: ...
    def lower_NotEq(self, ctx: LoweringState, node: ast.NotEq) -> Result: ...
    def lower_NotIn(self, ctx: LoweringState, node: ast.NotIn) -> Result: ...
    def lower_comprehension(
        self, ctx: LoweringState, node: ast.comprehension
    ) -> Result: ...
    def lower_ExceptHandler(
        self, ctx: LoweringState, node: ast.ExceptHandler
    ) -> Result: ...
    def lower_arguments(self, ctx: LoweringState, node: ast.arguments) -> Result: ...
    def lower_arg(self, ctx: LoweringState, node: ast.arg) -> Result: ...
    def lower_keyword(self, ctx: LoweringState, node: ast.keyword) -> Result: ...
    def lower_alias(self, ctx: LoweringState, node: ast.alias) -> Result: ...
    def lower_withitem(self, ctx: LoweringState, node: ast.withitem) -> Result: ...
    if sys.version_info >= (3, 10):
        def lower_Match(self, ctx: LoweringState, node: ast.Match) -> Result: ...
        def lower_match_case(
            self, ctx: LoweringState, node: ast.match_case
        ) -> Result: ...
        def lower_MatchValue(
            self, ctx: LoweringState, node: ast.MatchValue
        ) -> Result: ...
        def lower_MatchSequence(
            self, ctx: LoweringState, node: ast.MatchSequence
        ) -> Result: ...
        def lower_MatchSingleton(
            self, ctx: LoweringState, node: ast.MatchSingleton
        ) -> Result: ...
        def lower_MatchStar(
            self, ctx: LoweringState, node: ast.MatchStar
        ) -> Result: ...
        def lower_MatchMapping(
            self, ctx: LoweringState, node: ast.MatchMapping
        ) -> Result: ...
        def lower_MatchClass(
            self, ctx: LoweringState, node: ast.MatchClass
        ) -> Result: ...
        def lower_MatchAs(self, ctx: LoweringState, node: ast.MatchAs) -> Result: ...
        def lower_MatchOr(self, ctx: LoweringState, node: ast.MatchOr) -> Result: ...

    if sys.version_info >= (3, 11):
        def lower_TryStar(self, ctx: LoweringState, node: ast.TryStar) -> Result: ...

    if sys.version_info >= (3, 12):
        def lower_TypeVar(self, ctx: LoweringState, node: ast.TypeVar) -> Result: ...
        def lower_ParamSpec(
            self, ctx: LoweringState, node: ast.ParamSpec
        ) -> Result: ...
        def lower_TypeVarTuple(
            self, ctx: LoweringState, node: ast.TypeVarTuple
        ) -> Result: ...
        def lower_TypeAlias(
            self, ctx: LoweringState, node: ast.TypeAlias
        ) -> Result: ...

class NoSpecialLowering(FromPythonAST):
    pass
