from .dce import DeadCodeElimination as DeadCodeElimination
from .fold import ConstantFold as ConstantFold
from .alias import InlineAlias as InlineAlias
from .inline import Inline as Inline
from .getitem import InlineGetItem as InlineGetItem
from .getfield import InlineGetField as InlineGetField
from .apply_type import ApplyType as ApplyType
from .call2invoke import Call2Invoke as Call2Invoke
from .cfg_compactify import CFGCompactify as CFGCompactify
